library(ggplot2)
pl <- ggplot(mtcars,aes(x=wt,y=mpg))+ geom_point()
print(pl)
theme_set(theme_minimal())
pl <- ggplot(mtcars,aes(x=wt,y=mpg))+ geom_point()
print(pl)
pl <- ggplot(mtcars,aes(x=wt,y=mpg))+ geom_point()
print(pl + theme_dark())
library(ggthemes)
print(pl +theme_economist())
print(pl + theme_fivethirtyeight())
print(pl + theme_wsj())
