install.packages("tidyverse")
install.packages("funModeling")
install.packages("Hmisc")
library(funModeling)
library(tidyverse)
library(Hmisc)
data=heart_disease %>% select(age, max_heart_rate,thal, has_heart_disease)
glimpse(data)
df_status(data)
freq(data)
profiling_num(data)
plot_num(data)
describe(data)
library(ggplot2)

