mat <- matrix(1:25, byrow = T, nrow = 5)
mat

#ELEMENT BY ELEMENT BASIS
mat*2#PRODUCT
mat/2#DIVISION
mat^2#RAISED TO POWER OF
1/mat#RECIPROCAL

#LOGICAL MATRIX
mat>15#RETURNS MATRIX OF LOGICAL OPERATIONS

#FILTER
mat[mat>15]#RETURNS VECTOR WITH ALL TIMES IT IS TRUE

mat+mat#ADDITION OF TWO MATRICES
mat/mat#DIVISION
mat^mat#RAISED
mat*mat#ELEMENT BY ELEMENT MULTIPLICATION
mat %*% mat#TRUE MUTIPLICATION
